### ISSUE TITLE
Kompilieren unter Linux

### ISSUE THREAD

**Issue by vdagamb** [mdorenkamp/fhemduino#36]
Hi,
Bin gerade dabei, den ersten FHEMduino zu basteln.
habe bereits die Pearl Module installiert und die FW runter geladen. Das kompilieren ist für die Windows IDE erklärt, habe keinen Windows-Rechner zur Verfügung ... das Linux-Vorgehen ist wahrscheinlich so trivial, das es als bekannt vorausgesetzt wird. Vielleicht eine Zeile ins README.me mit welchem Befehl kompiliert werden soll (das einzige mir bekannte 'make' etc. ist es mit Sicherheit nicht :-)
Vielen Dank!
Bernd

**Comment by mdorenkamp** [comment]
Ich habe das ganze mit inotool (http://inotool.org/) gebaut.

**Comment by mdorenkamp** [comment]
zur info, ich arbeite nicht mehr aktiv an den modulen, ich habe das ganze mittlerweile auf MQTT umgestellt (FHEMduino -seriell->NodeRed->mosquitto->FHEM). im forum gibt es einige posts dazu

**Comment by vdagamb** [comment]
DAnke für die schnelle Antwort ... Ino habe ich auch gerade gefunden und lade gerade pip
ciao,
Bernd
